---
  - name: Installation of java and configuration of  tomcat server
    hosts: all
    gather_facts: false
    become: yes
    tasks:

     - name: pause the playbook for 5 minute
       pause:
         minutes: 5
     - name: deploy the war file into tomcat server
       copy: 
         src: $WORKSPACE/sample.war
         dest: /opt/tomcat/apache-tomcat/webapps
...
