---
  - name: Installation of java and configuration of  tomcat server
    hosts: all
    gather_facts: false
    become: yes
    tasks:

     - name: pause the playbook for 5 minute
       pause:
         minutes: 1
     - name: deploy the war file into tomcat server
       copy: 
         src: /var/lib/jenkins/workspace/project01/sample.war
         dest: /opt/wildfly-11.0.0.Final/standalone/deployments
...
